### ISSUE TITLE
fix missing image "Screenshot-MediaSuite-WordCloud-resourceviewer.png"

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#11]
![Screenshot 2020-04-07 at 11 09 11 AM](https://user-images.githubusercontent.com/902958/78652886-9e1e5d00-78c2-11ea-835a-60ce70fc14e8.png)

in markdown:
`![Wordcloud van de  Top 100 meest voorkomende onderwerpen (toegekend door archivarissen) ](./Screenshot-MediaSuite-WordCloud-resourceviewer.png)`

**Comment by mwigham** [comment]
@roelandordelman did you commit this file to Github?
