### ISSUE TITLE
World map color range is confusing and misses color key

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#13]
![Screenshot 2020-04-07 at 11 12 35 AM](https://user-images.githubusercontent.com/902958/78653159-040ae480-78c3-11ea-9e8b-2bd30b720d7b.png)

Locations which have zero mentions are coloured green, which is not continuous with the otherwise blue colour scale in use. This is confusing as it may signal that green countries have mentions while they haven't. It would be better to use white as colour for non mentioned countries.

also this visualisation should contain a key to indicate which shades of colour signify which intensity. I think a previous version contained a key like this?

**Comment by mwigham** [comment]
The changes were made at Roeland's request, including removing the key

**Comment by phivk** [comment]
@roelandordelman please see my comments above. I think we sacrificed readability by removing the key and changing the colour scale.

**Comment by mwigham** [comment]
@roelandordelman What are we going to do about this issue? Key/no key, different colour scale?

**Comment by roelandordelman** [comment]
@mwigham small key then + I like the contrast but I don't care if you turn it around or use 2 other colours
