### ISSUE TITLE
About Page text needs to be updated to mirror recent updates to DWDD content

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#14]

**Comment by MurielVP** [comment]
I corrected little things. This is the final text:

The CLARIAH Media Suite gives researchers access to Dutch multimedia archives from, among others, Netherlands Institute for Sound and Vision, Eye Film Institute, DANS, Meertens Institute and National Library. 

The Media Suite tools offer the core functionalities needed for research with these data and to generate “data stories” based on interesting facts and figures that are extracted from these data. 

Media Suite Data Stories serves as a platform for presenting various types of such data stories. They can be part of a research topic that scholars are working on in the Media Suite, the outcome of a Data-A-Thon with students, or inspired by events in the news.

@phivk Please link ‘CLARIAH Media Suite’ to https://mediasuite.clariah.nl/

**Comment by phivk** [comment]
closed via https://github.com/beeldengeluid/data-stories/commit/916a5d89ff23b59ddc638517a7d883eb87259878
