### ISSUE TITLE
add datastories link to media suite navbar menu

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#19]
link: http://mediasuitedatastories.clariah.nl/

**Comment by phivk** [comment]
@jblom is this something you could action?

**Comment by roelandordelman** [comment]
@jblom this issue has a bit of urgency (as the data stories are not easy to find currently) so I was also wondering when this could be taken up.

**Comment by jblom** [comment]
@roelandordelman well I suggest you and @frankstrater discuss where exactly to incorporate this, so Frank can extend the navbar. Then all we have to do is deploy it to production. @MartijnBNG and myself are pretty much ready for this (so far we have deployed the newly integrated site on TEST, but it should be ready for PROD too)

**Comment by frankstrater** [comment]
Discussed this with Roeland and decided a while ago to make Data Stories the first "feature" in the carousel on the homepage, as it is an external link.

**Comment by phivk** [comment]
> Discussed this with Roeland and decided a while ago to make Data Stories the first "feature" in the carousel on the homepage, as it is an external link.

good solution 👍
