### ISSUE TITLE
publish Kennissessie DWDD Data Story as blog post

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#25]
- [x] Philo to start shared document and enter first draft 
- [x] Mari to enter first draft 
- [x] Philo to proofread draft
- [x] Mari to proofread draft
- [x] Philo to incorporate feedback
- [x] Philo to create landscape hero image of Matthijs VN
- [x] Muriel to proofread final version

**Comment by phivk** [comment]
@mwigham Here's the shared doc w first draft:
https://docs.google.com/document/d/1lS4WFUXF_8MjXNKB3vSf5Sc6PxJ4OCIbFCeTDH7hMCo/edit#heading=h.xfxo0ftjk4jn

**Comment by mwigham** [comment]
@phivk I've put in my bit, too long but we can prune it at the next stage

**Comment by phivk** [comment]
ok thanks! my turn to do some proofreading!

**Comment by phivk** [comment]
@mwigham I've done my bit of proofreading 🙂

**Comment by mwigham** [comment]
@phivk thanks, my turn then!

**Comment by mwigham** [comment]
@phivk I've addressed your points and also put in some comments on your piece, can you take a look please? As it is a 'making of' story, I've also added in a little more discussion of how we had to be careful with incomplete data, and how the software itself could influence the results.

**Comment by phivk** [comment]
thanks @mwigham I've resolved all comments and feedback and passed it on to @MurielVP for final proofreading :)

**Comment by phivk** [comment]
published:
https://www.beeldengeluid.nl/en/knowledge/blog/making-dwdd-data-story
