### ISSUE TITLE
support i18n for DWDD story and website

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#26]
- [x] research [options](https://www.gatsbyjs.org/docs/localization-i18n/) and choose i18n library
- [x] get translations from Muriel for intro and about texts
- [x] integrate translated DWDD article
- [x] enable routing for `en` and `nl` versions
- [x] add language switch
- [x] deploy

**Comment by phivk** [comment]
@MurielVP could you provide me with Dutch versions for the following texts:

<img width="1792" alt="Screenshot 2020-06-15 at 5 00 49 PM" src="https://user-images.githubusercontent.com/902958/84673860-83074380-af2a-11ea-977e-0be6699d72f2.png">

<img width="1792" alt="Screenshot 2020-06-15 at 5 01 04 PM" src="https://user-images.githubusercontent.com/902958/84673851-800c5300-af2a-11ea-9b42-a0bf000b12ef.png">

**Comment by MurielVP** [comment]
Tekst in header: 
Verhalen uit multimediale archieven, mogelijk gemaakt door de Media Suite

**Comment by MurielVP** [comment]
About in NL >> Over Data Stories

**Comment by MurielVP** [comment]
![image](https://user-images.githubusercontent.com/63304024/86109104-4d369300-bac4-11ea-9a46-2daed32fc97b.png)

**Comment by phivk** [comment]
text version:

> De CLARIAH Media Suite geeft onderzoekers toegang tot Nederlandse multimediale archieven uit de collecties van onder andere het Nederlands Instituut voor Beeld en Geluid, Eye Film Institute, Meertens Instituut, DANS en de Koninklijke Bibliotheek.
> 
> De Media Suite biedt de kernfunctionaliteiten die nodig zijn voor onderzoek met deze multimediale data en het genereren van ‘dataverhalen’ op basis van interessante feiten en cijfers die uit deze data worden verkregen.
> 
> Media Suite Data Stories dient als platform voor het presenteren van verschillende soorten van dergelijke dataverhalen. Ze kunnen deel uitmaken van een onderzoek waar wetenschappers aan werken in de Media Suite, het resultaat zijn van een Data-A-Thon met studenten, of geïnspireerd zijn door gebeurtenissen in het nieuws.

**Comment by phivk** [comment]
> Ik zou 'Welcome' weglaten. Dat is 'outdated and frowned upon' in webcopywriting. 
> 
> Mijn vertaling voor: Take a look at the data stories and data visualisations resulting from the metadata of multimedia archive material from the collections maintained at leading Dutch heritage institutions. 
> 
> >> Bekijk dataverhalen en -visualisaties die voortvloeien uit de metadata van multimediaal archiefmateriaal uit de collecties van toonaangevende Nederlandse erfgoedinstellingen.
