### ISSUE TITLE
as an editor I would like pushes to the repo to trigger a fresh deploy so I can publish my changes quickly and reliably

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/data-stories#30]
This could be solved fairly straight forward via one of the following:
- [Vercel Git integration](https://vercel.com/docs/git-integrations) (in use for MediaScape)
- [Netlify](https://www.netlify.com/github-pages-vs-netlify/)
- some build & deploy workflow via GitHub Actions ([some](https://github.com/marketplace/actions/github-pages-action) [example](https://github.com/enriikke/gatsby-gh-pages-action) [actions](https://github.com/marketplace/actions/publish-gatsby-site) to investigate)
- https://surge.sh/

to be discussed between @phivk and @MartijnBNG

**Comment by jblom** [comment]
@phivk let's discuss this with @MartijnBNG

**Comment by phivk** [comment]
@jblom neem jij een kijkje naar de opties?

**Comment by phivk** [comment]
ik heb net [Vercel](https://vercel.com/pricing), [Netlify](https://www.netlify.com/pricing/) en [Surge](https://surge.sh/pricing) pricing gecheckt gecheckt en met 19 a 20 $ p member p month (surge 30$ flat p month) is het inderdaad niet iets dat we zomaar even aansluiten 😉 

Met @MartijnBNG in het team zou een custom workflow met GH Action misschien niet eens zo'n gekke optie zijn...

wat vlugge impressies van Vercel en Netlify:

**Vercel PROs**
+ kan ook Server Side Rendering doen (oa handig met Next en Nuxt)
+ fijne zero-config setup
+ fijne serverless function support

**Netlify PROs**
+ also offers git-based Netlify CMS
+ additional features for forms, identity, analytics
+ also has serverless Netlify functions

meer vergelijkend waren onderzoek:
https://www.lambrospetrou.com/articles/battle-of-jamstack-platforms-netlify-vercel-aws/

We zouden Vercel en Netlify makkelijk gratis kunnen uitproberen om meer te leren.

**Comment by phivk** [comment]
@jblom dit is een interessant perspectief van het Australische DX Lab, over hun move naar serverless mbv oa Vercel (formerly Zeit)
https://dxlab.sl.nsw.gov.au/blog/going-serverless/

**Comment by jblom** [comment]
@phivk ok ik heb je bronnen net allemaal gelezen en heb wat zitten nadenken en tekenen over wat voor een impact dit heeft op de infrastructuur. Via een hangout even bijpraten?

**Comment by phivk** [comment]
following up to our convo today @jblom : I'll draft a message to explain our motivation and use of Vercel in an email.
then I'll create an org account for myself linked to the BenG GitHub account and I'll be in touch about payment

**Comment by phivk** [comment]
Deployment is now set up and managed via vercel:
https://vercel.com/beeldengeluid/data-stories
